version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nextjs-app
    ports:
      - '3000:3000'
    depends_on:
      - dev-db
    environment:
      DATABASE_URL: 'postgresql://travel_user:travel_admin@dev-db:5432/ai_travel'
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/frontend
    tty: true
    stdin_open: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: hono-api
    ports:
      - '8787:8787'
    depends_on:
      - dev-db
    environment:
      DATABASE_URL: 'postgresql://travel_user:travel_admin@dev-db:5432/ai_travel'
    volumes:
      - .:/app
      - ./prisma:/app/prisma
    working_dir: /app/backend
    tty: true
    stdin_open: true

  dev-db:
    container_name: postgres
    hostname: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'travel_user'
      POSTGRES_PASSWORD: 'travel_admin'
      POSTGRES_DB: 'ai_travel'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
