version: '3.8'
services:
  dev-db:
    container_name: postgres
    hostname: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'travel_user'
      POSTGRES_PASSWORD: 'travel_admin'
      POSTGRES_DB: 'ai_travel'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
